### PR TITLE
Update to 1.20.1

### PR DESCRIPTION
**Pull request by Egietje**
Hey!

I've updated the mod to 1.20.1, mainly for my own use. Because Lodestone hasn't been updated to 1.20.1, I've had to deleted all features that require lodestone. For me this was fine, as I wanted what I could get for now. I thought you guys might be interested in how I updated some things.

### CODE REVIEW

**Comment by doctor4t** [comment]
if this is destructive, I don't think I can merge it in main. I don't think it has much purpose having it merged even as its own branch on the main repo too if it's missing all the lodestone dependant features, which is a lot of them.

**Comment by Egietje** [comment]
Fair enough, I might look into trying to update Lodestone at some point, in that case I could update everything :)

**Comment by MotMomet** [comment]
> Fair enough, I might look into trying to update Lodestone at some point, in that case I could update everything :)

can u also try to update dynamic surruondings mod to 1.20 or 1.20.1?

**Comment by MotMomet** [comment]
> Hey!
> 
> I've updated the mod to 1.20.1, mainly for my own use. Because Lodestone hasn't been updated to 1.20.1, I've had to deleted all features that require lodestone. For me this was fine, as I wanted what I could get for now. I thought you guys might be interested in how I updated some things.

how can i build it? im getting errors can u share the jar?

**Pull request closed without merging**
