### PR TITLE
Futureproofing copyright stuff thingies

### PR DESCRIPTION
**Pull request by Hedreon**
I don't know how to call them

### CODE REVIEW

**Comment by Pyrofab** [comment]
FYI, the date on these files is not legally required, it's more for information's sake. In fact, the starting date should be 2021 :upside_down_face:

**Comment by Hedreon** [comment]
> FYI, the date on these files is not legally required, it's more for information's sake. In fact, the starting date should be 2021 🙃

so I only had to change the date on the license only?

**Comment by Pyrofab** [comment]
It's neither legally required on the readme nor the license, so there's not really any reason to change them before the new year comes around. That said, I'll leave it to doctor4t to actually decide whether they want to merge this now or not.

**Comment by doctor4t** [comment]
I'll forget about this later otherwise, thanks for the PR

**Pull request merged**
