### PR TITLE
Update to 1.19.4

### PR DESCRIPTION
**Pull request by SzczurekYT**
Hello
Here's an update for 1.19.4.
No big changes, overall the code is just adopted to changes Mojang made, to make it compile.
Changes:
- I updated the dependencies
- Build error was telling me to update gradle to 8.1 so I did that.
- They removed the BlockPos constructor that takes non int values, and replaced it with BlockPos.create(x,y,z) so I had to replace almost every `new BlockPos(x,y,z)` with `BlockPos.create(x,y,z)` and add `Math.floor(num)` here and there.
- Registry was split into three classes, adopted to that.

From initial testing everything seems to work.
Feel free to ask for changes if I did something wrong, I'm happy to help.

### CODE REVIEW

**Comment by ViTulyankin** [comment]
@SzczurekYT, is there any way to build mod by myself?

**Comment by SzczurekYT** [comment]
> @SzczurekYT, is there any way to build mod by myself?
> 
> UPDATE: I tried to build it using `gradlew build`, but it was unsuccessful due to outdated version of Gradle
> 
> > * What went wrong:
> >   An exception occurred applying plugin request [id: 'org.quiltmc.loom', version: '1.+']
> > 
> > > Failed to apply plugin 'org.quiltmc.loom'.
> > > > You are using an outdated version of Gradle (7.5.1). Gradle 8.1 or higher is required.

I changed the version of gradle to 8.1, I think you might accidentally pull the main branch, that is defualt and has no changes.
More people will probably want this, so I made a release you can use until official release.
For now you can download a 1.19.4 version from here https://github.com/SzczurekYT/Effective/releases/tag/1.7%2B1.19.4

**Comment by ViTulyankin** [comment]
Thanks a lot for all your work!

**Comment by ViTulyankin** [comment]
@SzczurekYT, i tested it and found two bugs.

First, for some reason splashes always occure in the center of four blocks. Video demonstration: https://clck.ru/34gydG

Second, the cascade sound is really quiet, even with 200 volume multiplier. Video demonstration: https://clck.ru/34gymR

Also, allay trail is not working with shaders, but i think it doesn't work in the 1.19.3 version too.

**Comment by SzczurekYT** [comment]
Good to know. Mojang yeeted half of their math code and replaced it with JOML lib, so some things might not be correct.
I'm away from home this week, so I probably won't do anything now.
I also see that Rat returned.
@doctor4t are you going to use this?

**Comment by Cm4nXD** [comment]
Is it possible for you to update this to 1.20?

**Comment by SzczurekYT** [comment]
I'm a bit busy now, but if I had some time  I probably could, but the thing is:
Is the @doctor4t or anyone else willing to accept that PR? This is my second PR for Ladysnake and both haven't really received any interest from the developers. I'm not sure if I want to make another one if it's going to be ignored too.
also
I know currently there are merge conflicts, and I will fix them as long as you are willing to accept this PR.

**Comment by doctor4t** [comment]
Hi, sorry I missed this. Does this update include all the new Effective 2.0 stuff?

**Comment by SzczurekYT** [comment]
As of now it doesn't, but as you are interested in this I will update the PR when I will have some free time. For now consider it as work in progress.

**Comment by doctor4t** [comment]
Alright. I rewrote 90% of the code for Effective 2.0 so it might also be a good idea to check the changes that were made to the code if you wanna port to 1.20. Did a lot of things change cause it might be faster for me to do it if the changes are minimal

**Comment by SzczurekYT** [comment]
> Alright. I rewrote 90% of the code for Effective 2.0 so it might also be a good idea to check the changes that were made to the code if you wanna port to 1.20.
Yeah, with such changes my code in it's current state is probably useless and the port needs to be rewritten too.
> Did a lot of things change cause it might be faster for me to do it if the changes are minimal

Well they changed some things:
>  (From the original comment)
> * They removed the BlockPos constructor that takes non int values, and replaced it with BlockPos.create(x,y,z) so you have to replace almost every `new BlockPos(x,y,z)` with `BlockPos.create(x,y,z)` and add `Math.floor(num)` here and there.
> * Registry was split into three classes.
* The removed a huge part of their math code and replaced it with the JOML library, so in some cases you need to spend some time to find adequate method that does what the previous code did. This can be done by comparing 1.19.2 code with 1.19.3/4 code and checking what they replaced something with.

**Comment by tigris62716** [comment]
so if i understand this correctly @SzczurekYT you are working on updating this yourself? not rat?

**Comment by bIankface** [comment]
Also there isn't a config option in the mod settings when clicking on the effective icon, awesome mod though :)

**Comment by SzczurekYT** [comment]
For all you asking and wondering:
Currently this PR us useless, since the mod has been rewritten, so my update to 1.19.4 of it needs a rewrite too.
I also don't have too much time as of now, so I'm closing this PR. If I will have some time then I will update Effective 2.x to 1.19.4 and make a new PR.
What about 1.20? In my opinion I think the mod should get 1.19.4 update first so that people who aren't ready to update can have it too, and then to 1.20.

**Comment by SzczurekYT** [comment]
image
Why did I....
I accidentally ported the old Effective to 1.19.4 instead of the new one. (I used a wrong base or something like that, realized just when finished and noticed the new features are absent 😫)
Now I'm starting a third try to get this updated to 1.19.4.
A new PR coming soon 😃

**Comment by Egietje** [comment]
For those interested, I updated to 1.20.1 in #197 (however, maybe I should've gotten more sleep before doing it because having BlockPos.create() is much better than casting the arguments to ints)

**Pull request closed without merging**
