### PR TITLE
Update 1.19.4

### PR DESCRIPTION
**Pull request by SzczurekYT**
Hello
I'm back, with an update to 1.19.4 for Effective 2.x
All the changes I made are grouped into few big commits that have a description explaining what and why it was changed. (Except from few small ones where I missed something). I recommend taking a look a them and reading the descriptions.

I tested everything from the new showcase video and made sure it works. There is only one thing that is broken - ghast fireball ultrakill, the white particles don't show up, the screen only freezes for these few ticks. I have no idea how to fix, but it's probably something related to changes made to LodestoneLib in 1.19.3/4 version. (The 1.19.3 branch supports 1.19.4, and arathain said he will be updating it to 1.20 soon). Maybe you will know? You probably should take look at [ScreenParticleParryRenderEnforcer](https://github.com/Ladysnake/Effective/compare/main...SzczurekYT:2.x-1.19.4?expand=1#diff-a6e3722fe80a44527784a8483bbedf48bf71fb0e4810d4a999f8cc01fd20b064), as the class it targets got a rewrite and the mixin it's probably not correct now.

### CODE REVIEW

**Comment by a-person1908** [comment]
I'm dumb sorry but how do I package this?

**Comment by bIankface** [comment]
Thanks alot! Is it possible if you could link a compiled version to this since I can't see, to figure our how to do it on a mac, thanks again!

**Comment by MasterMM007** [comment]
This doesn't work with Fabric right?

**Comment by SzczurekYT** [comment]
> This doesn't work with Fabric right?

No, it's just an update to 1.19.4, it's still on quilt.
It's a bit funny that now most of the mods is developed for fabric, but still most people run quilt because of the few mods that use it.

**Comment by a-person1908** [comment]
how do you package this?

**Comment by Kavin7000** [comment]
Are you planning on updating to 1.20.1?

**Comment by SzczurekYT** [comment]
Currently probably not, as I don't think I will be updating to 1.20 soon, so I don't have any motivation.

**Comment by KiloPetraGames** [comment]
Greetings! Is there any way that this can be modified to work in 1.19.3?

**Comment by ViTulyankin** [comment]
@SzczurekYT, is there any way to build mod by myself? (Dejavu?)
Or maybe you can make a release? :)

**Comment by SzczurekYT** [comment]
> @SzczurekYT, is there any way to build mod by myself? (Dejavu?) Or maybe you can make a release? :)

Since everyone is asking, here is a build.
[effective-1.7+1.19.4.zip](https://github.com/Ladysnake/Effective/files/12139870/effective-1.7%2B1.19.4.zip)
You need to rename it from .zip to .jar (because github doesn't allow uploading jars in comments).
@a-person1908  you have been waiting for this too.

**Comment by SzczurekYT** [comment]
> Greetings! Is there any way that this can be modified to work in 1.19.3?
You can try, it may work without any changes, but I don't guarantee that.

**Comment by ViTulyankin** [comment]
> Since everyone is asking, here is a build.
[effective-1.7+1.19.4.zip](https://github.com/Ladysnake/Effective/files/12139870/effective-1.7%2B1.19.4.zip)

But... Isn't it 1.7 version of this mod?

**Comment by ViTulyankin** [comment]
> Since everyone is asking, here is a build. [effective-1.7+1.19.4.zip](https://github.com/Ladysnake/Effective/files/12139870/effective-1.7%2B1.19.4.zip)

But... Isn't it 1.7 version of this mod?

**Comment by SzczurekYT** [comment]
> > Since everyone is asking, here is a build. [effective-1.7+1.19.4.zip](https://github.com/Ladysnake/Effective/files/12139870/effective-1.7%2B1.19.4.zip)
> 
> But... Isn't it 1.7 version of this mod?

Uh.. This feels so wrong. I think it's just a wrong number, it might get lost somewhere during porting, but I need to make sure.

**Comment by KiloPetraGames** [comment]
> > Greetings! Is there any way that this can be modified to work in 1.19.3?
> 
> @KiloPetraGames You can try, it may work without any changes, but I don't guarantee that.

Dang, doesn't seem to work. Is there a tutorial somewhere on how to build this? Where I can then swap out the game/dependency versions?

**Comment by SzczurekYT** [comment]
> > > Greetings! Is there any way that this can be modified to work in 1.19.3?
> > 
> > 
> > @KiloPetraGames You can try, it may work without any changes, but I don't guarantee that.
> 
> Dang, doesn't seem to work. Is there a tutorial somewhere on how to build this? Where I can then swap out the game/dependency versions?

Open an issue on my repo and send the error, I can try to help you there, so we don't clutter this PR.

**Comment by doctor4t** [comment]
I'll test this and merge it into a new 1.19.4 if it's good. Thanks for the contribution!

**Comment by SzczurekYT** [comment]
> I'll test this and merge it into a new 1.19.4 if it's good. Thanks for the contribution!

Great, most of the things should work.
Some dependency stuff changed recently, so make sure to pull the commit I added now.
I also can't build the project, as an error shows up `Failed to transform mod metadata file`, but might be just me, as gradle sometimes can get a bit tricky, and It worked before.

**Comment by KiloPetraGames** [comment]
> > > > Greetings! Is there any way that this can be modified to work in 1.19.3?
> > > 
> > > 
> > > @KiloPetraGames You can try, it may work without any changes, but I don't guarantee that.
> > 
> > 
> > Dang, doesn't seem to work. Is there a tutorial somewhere on how to build this? Where I can then swap out the game/dependency versions?
> 
> Open an issue on my repo and send the error, I can try to help you there, so we don't clutter this PR.

Apologies! I can't see an issues tab on your Repo, is there somewhere else we could communicate?

**Comment by SzczurekYT** [comment]
> > > > > Greetings! Is there any way that this can be modified to work in 1.19.3?
> > > > 
> > > > 
> > > > @KiloPetraGames You can try, it may work without any changes, but I don't guarantee that.
> > > 
> > > 
> > > Dang, doesn't seem to work. Is there a tutorial somewhere on how to build this? Where I can then swap out the game/dependency versions?
> > 
> > 
> > Open an issue on my repo and send the error, I can try to help you there, so we don't clutter this PR.
> 
> Apologies! I can't see an issues tab on your Repo, is there somewhere else we could communicate?

Oops, I forgot it's disabled for forks by default, try now.

**Comment by Spike-has-no-idea-how-to-code** [comment]
> 

Hey, I can’t build this either ( although I am completely unfamiliar on everything about this platform,Git, and Gradle) I learned how to do a build from a comment on a pull request for the Auditory mod on here, and I would like to use the updated 2.1 for 1.19.4, but I’m stuck with your only release for 1.7 because it fails when I try to build it. Maybe someone could tell me what I’m supposed to do? Maybe what worked for auditory won’t work with this, and that’s what’s stopping me. Anyway, please help but no rush

**Comment by SzczurekYT** [comment]
> > 
> 
> Hey, I can’t build this either ( although I am completely unfamiliar on everything about this platform,Git, and Gradle) I learned how to do a build from a comment on a pull request for the Auditory mod on here, and I would like to use the updated 2.1 for 1.19.4, but I’m stuck with your only release for 1.7 because it fails when I try to build it. Maybe someone could tell me what I’m supposed to do? Maybe what worked for auditory won’t work with this, and that’s what’s stopping me. Anyway, please help but no rush

Looks like the build error fixed itself, I saw gradle downloading new quilt loom versions, so probably quilt loom had a bug.

**Comment by Treetrain1** [comment]
> Looks like the build error fixed itself, I saw gradle downloading new quilt loom versions, so probably quilt loom had a bug.

Yes, Quilt Loom 1.3.2 fixed the `Failed to transform mod metadata file` error
it was due to Loom only ever checking for a QMJ5 (which isnt fully implemented) or an FMJ

**Comment by SzczurekYT** [comment]
> > Looks like the build error fixed itself, I saw gradle downloading new quilt loom versions, so probably quilt loom had a bug.
> 
> Yes, Quilt Loom 1.3.2 fixed the `Failed to transform mod metadata file` error it was due to Loom only ever checking for a QMJ5 (which isnt fully implemented) or an FMJ

Thanks for the details.

**Comment by doctor4t** [comment]
Been a while since I looked at this. Are the issues you mentionned originally fixed?

**Comment by SzczurekYT** [comment]
> > I was absent too. The only issue that I mentioned, is that there is no white flash on ghast ultrakill. It still isn't fixed, and I don't know how to fix that, so you have to do that yourself.
> 
> I've tested 1.20 version - water splashes are still pretty broken [#181 (comment)](https://github.com/Ladysnake/Effective/pull/181#issuecomment-1589319597)

I see, yes, that's still an issue.
I'll try to fix it soon.

**Comment by doctor4t** [comment]
Personally still can't build this, as it seems to be failing to find the Lodestone commit you put as the version.

**Comment by SzczurekYT** [comment]
> Personally still can't build this, as it seems to be failing to find the Lodestone commit you put as the version.
To test this I did a fresh clone of the 2.x branch with `git clone --single-branch -b 2.x-1.19.4 https://github.com/SzczurekYT/Effective` and it built successfully without any issues.
Maybe some cache issues?

**Comment by SzczurekYT** [comment]
> Personally still can't build this, as it seems to be failing to find the Lodestone commit you put as the version.

Oh wait, I yeeted my gradle cache and now I have this issue too.

**Comment by SzczurekYT** [comment]
Looks like the build on jitpack failed https://jitpack.io/com/github/Arathain/LodestoneLib-Quilt/70a03b920e/build.log

**Comment by doctor4t** [comment]
I love jitpack, I need to get arathain to start publishing Lodestone Quilt on the Ladysnake maven

**Comment by SzczurekYT** [comment]
Can you please make your next minecraft video about kidnapping Arathain until he publishes his libs to some kind of maven repo?
Recently I wanted to go back to this PR and finish off it, but broken Jitpack quickly made sure I leave the thing again.

**Comment by Pyrofab** [comment]
Can relate, ended up publishing the latest version to our repo myself.

I have merged this PR as part of the 1.20.1 update, huge thanks for this.

**Comment by Pyrofab** [comment]
Also I haven't worked on the mod enough to know how to fix the issue you mentioned (if it's still there), so if you have an idea a PR would be very appreciated =)

**Pull request merged**
