### PR TITLE
Bug fixes and config update

### PR DESCRIPTION
**Pull request by wallamide**
Fixes Issues #38, #39, and #40/#46 
Issue #40 fix provided by rbroderi in the comments

### CODE REVIEW

**Comment by armuell** [comment]
+9001 hottest pull request of 2022 so far

**Comment by armuell** [comment]
any chance you could post a build of this pr? I just want to turn the sound of waterfalls down without having to set all ambient sounds to 3% lol

**Comment by doctor4t** [comment]
Tested the PR, and it seems good, but my problem with it is that waterfall such as this are no longer counted as waterfalls.
image
If you were to fix that, I'll gladly merge the PR :)
Thanks for the contribution

**Comment by wallamide** [comment]
Thanks for taking the time to check this out! I'm currently working a fix so more waterfalls are counted as waterfalls and will get back to you with the update

**Comment by TheDerpu0ne** [comment]
These would be cool to have

**Comment by Chris6ix** [comment]
Just saw this, and it would also fix the issue (#62) I just created :)
Any updates on this?

**Comment by Akairilia** [comment]
any updates? game keeps crashing, i need the fix now

**Pull request closed without merging**
