### PR TITLE
[fix][feat] limits the sound of waterfall

### LINKED ISSUE #95: waterfall noises heard from long distances + too loud
The waterfall noises from the mod are being heard from a distance it shouldn't be. Over 100+ blocks away and they're still audible from that distance. Seems everywhere you travel, the water noises are too loud compared to every other sound and from testing the mod, it seems once you hear the waterfall once, it stays with you forever loses some of its volume until you relog.

Youtube video showing issue in-game: https://www.youtube.com/watch?v=MfYTQPPYma4&ab_channel=Farrais

### LINKED ISSUE #100: waterfalls noise almost everywhere
**waterfalls are being heard from very far distance + its being heard from caves.**
I have a water filled cave in my survival world just under my base and village and I can hear the waterfall sound from very far away above the surface while its deep down in the caves.
this started bothering me but I just turned off all the water particles and its stopped however no sound well ever be heard for water from the mod. 
I suggest adding few confg sittings to change the distance and loudness of the waterfalls aside of the particles and having the hearing distance adjustable so after an amount of blocks in all direction u should not hear it. but this doesn't really matter if u can chose the distance u want to hear it from, and confg how loud its.

### PR DESCRIPTION
**Pull request by lonefelidae16**
resolve #95 , resolve #100

Add classes:
* ladysnake.effective.client.sound.DistancedSoundInstance
that can be changed its volume by Player’s position.
* ladysnake.effective.client.sound.WaterfallSoundInstance
refers to `ModConfig#waterfallSoundVolume`.

Add configs:
* ladysnake.effective.client.ModConfig
  - `waterfallSoundDistanceBlocks`, default = 36
  - `waterfallSoundVolume`, default = 100

Light refactoring for `WaterfallCloudGenerators.java`, please check:
* replaced volatile var `adding` with `generators` enclosed in synchronized.
* the conditions of adopted `early return` is correct or not, especially `if` statement.

The built jar can be found on my repository: [lonefelidae16:Effective/fix/water-falls-sound](https://github.com/lonefelidae16/Effective/commit/dd4b86d18866228d6988b38a58d1933b3e046dc8#commitcomment-77975168)

### CODE REVIEW

**Comment by Hedreon** [comment]
I get an error with the `super` line in the `DistancedSoundInstance` class which is:

`Cannot resolve method 'super(SoundEvent, SoundCategory, float, float, BlockPos)'`

Any way to fix this?

**Comment by lonefelidae16** [comment]
> I have found a [fix](https://github.com/lonefelidae16/Effective/commit/93c6432b227de48574e57164afef86d5baf5120d#diff-17ce8cd4f94e4a9a5774452c7319a66123c80a6449542a46c818aa5ed01bedf0) for versions 1.19+.

yep this PR is targeted to MC1.18.2. Please merge the diff of [the tag 1.2.2 (MC1.19.x)](https://github.com/Ladysnake/Effective/commit/308a3171dcd232adcb4518689e6a24069a3a309c) if necessary.

**Comment by lonefelidae16** [comment]
update: now targets to 1.19.2, I changed the target branch to `main`.

* `en_us.json`
  - update prefix <code>**MODID**.midnightconfig.*settingName*</code>

* `EffectiveConfig.java`
  - `long lapisBlockUpdateParticleChance` was changed the type to `int` so that it can be changed by ModMenu

**Comment by doctor4t** [comment]
Do these changes affect the default behaviour or do they only add config options?

Also, have you tested if it functions properly with Sound Physics Remastered?

**Comment by lonefelidae16** [comment]
> Do these changes affect the default behaviour or do they only add config options?
>
> Also, have you tested if it functions properly with Sound Physics Remastered?
> 
> I already had implemented my own version of options, but if those ultimately prove to be better I'll revert my commits to merge this.

I noticed that the default behaviour including these options and config names did not work well, but there are some conflicts. I also have not tested with Sound Physics Remastered.
I’ll check the compatibility with it and try to fix conflicts.

**Comment by lonefelidae16** [comment]
update: option `waterfallSoundVolume` was removed, `waterfallSoundDistanceBlocks` is the main change.

I tried Sound Physics Remastered, my instance works well.

There are still issues related to #95 and #100, where the sound of the waterfall is heard from very far away. This PR will be fixed these.

**Comment by lonefelidae16** [comment]
Curiously, I thought this PR’s waterfall was very quiet, but I noticed that the volume was 10 times louder in the main branch. I’ll adjusting volumes...

**Comment by lonefelidae16** [comment]
I hope I have been able to limit the sound of the waterfall while keeping it as close to the default behavior as possible.

**Comment by doctor4t** [comment]
Seems like a better version of my changes, so I'll merge it. I'll only request that the default value is higher (150) and that the max config value should be increased to something like 300-400 if people like the very far away sounds.

**Comment by lonefelidae16** [comment]
> Seems like a better version of my changes, so I'll merge it. I'll only request that the default value is higher (150) and that the max config value should be increased to something like 300-400 if people like the very far away sounds.

Ah... You are absolutely right.

If some people don't want to hear a waterfall unless they get close, it is not surprise that some people would want to be able to hear it at a distance. I overlooked that.

Thank you for merging @doctor4t !

**Pull request merged**
