### PR TITLE
Added russian locale

### PR DESCRIPTION
**Pull request by zatrit**

### CODE REVIEW

**Comment by Felix14-v2** [comment]
> I'm russian

Well, then try to explain all **this**.
Screenshot_20220601-175459

**Comment by Felix14-v2** [comment]
I'll give you a good advice: at least check the logic of what you got when translating.

**Comment by zatrit** [comment]
> I'll give you a good advice: at least check the logic of what you got when translating.

Where was i wrong now?

**Comment by Felix14-v2** [comment]
Well, tell me, When updating, which object does lapis lazuli particles appear?

And I don't understand why do something that has already [been done](https://github.com/Ladysnake/Effective/pull/78)  before? If you don't like the translation that already exists, just start a review.

**Comment by zatrit** [comment]
> Well, tell me, When updating, which object does lapis lazuli particles appear?
> 
> And I don't understand why do something that has already [been done](https://github.com/Ladysnake/Effective/pull/78) before? If you don't like the translation that already exists, just start a review.

You are right

**Pull request closed without merging**
