### PR TITLE
Added 2 settings to enable/disable waterfall and splashes particles.

### PR DESCRIPTION
**Pull request by devpelux**
I've added two settings to enable and disable the effects.
For example I love the splashes but I don't really need the waterfall effect, even if it is still very nice. :)

The settings are `enable-waterfall-particles` and `enable-splash-particles`.

### CODE REVIEW

**Comment by PsychoBreadstick** [comment]
I believe a separate tab in the options menu labeled "Effective" would be good, and just having all the options in there.

**Comment by devpelux** [comment]
Maybe is much better an integration with Mod Menu, a separate tab in the Options menu only for this I think is useless...

**Comment by PsychoBreadstick** [comment]
> Maybe is much better an integration with Mod Menu, a separate tab in the Options menu only for this I think is useless... However I leave to the maintainer to choose what is better to do.

Not everyone uses mod menu. I don't see the point of having to download another mod just to be able to disable 1 or 2 settings.

**Comment by Pastell** [comment]
> > Maybe is much better an integration with Mod Menu, a separate tab in the Options menu only for this I think is useless... However I leave to the maintainer to choose what is better to do.
> 
> Not everyone uses mod menu. I don't see the point of having to download another mod just to be able to disable 1 or 2 settings.

Everyone either uses Mod Menu, or should be using Mod Menu. I see vanishingly few reasons not to. If you don't want to download a mod to change settings, edit the config file manually.

**Review by Pyrofab — APPROVED** [review]
Looks good to me, thanks for your contribution !

**Pull request merged**
